server {
    server_name app.com;
    root /var/www/kuesioner-app;
    index index.php index.html;

    autoindex off;

    # Lindungi folder backend
    location ~* /(api|includes)/ {
        deny all;
        return 403;
    }

    # Lindungi file sensitif
    location ~* \.(env|sql|ini|log|bak|sh|yml|json|md)$ {
        deny all;
        return 403;
    }

    # PHP handler
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;  # sesuaikan versi PHP kamu
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # ROUTER utama: arahkan semua URL ke index.php
    location / {
        try_files $uri $uri/ /index.php;
    }

    access_log /var/log/nginx/app-access.log;
    error_log /var/log/nginx/app-error.log;

    error_page 404 /404.html;

    location = /404.html {
        root /var/www/kuesioner-app;
    internal;
}

}
